const sample_dreams = {
    list: [
        {
            ref: "This Jungian Life Podcast, episode 188",
            text: "It’s a bright clear day, and I’m in a forest. I’m walking around when I spot these hybrid creatures, both boar and human, or humans wearing boar heads as helmets. They are absolutely terrifying, and I try to hide from them in the brush. I watch them. Suddenly, one veers off from the rest and leans over and defecates or vomits from its chest. It’s violent and disgusting. The creature seems weakened, sick. Then I’m walking again, trying to get away from the creatures, but they spot me– at least one of them does. I am not afraid now and assume we will fight. There’s a group of swords on the ground–more like big serrated knives–, and I pick one up. The creature and I duel, and I cut it several times. I’m confident in my victory, but then I’m nicked on the face. I’m worried about this; maybe it’s worse than I know. Then the dream jumps, and I’m in a dark bathroom examining the cut in the mirror. It’s a scratch. The boar creature is here with me, but she’s a beautiful brunette woman, and it’s clear we’re lovers. The feeling now is very light and romantic and easy."
        },
        {
            ref: "This Jungian Life Podcast, episode 174",
            text: "Had a dream about a close friend. She had committed a murder, and there was a police detective asking her questions. She had some sort of tracker device that she was holding in her hand most of the dream. She lied to the detective and said she only had it because of her work, and she hadn’t even turned it on yet. The policeman wanted to check her tracker to confirm she wasn’t at the scene of murder. She kept making up excuses as to why she couldn’t give it to him. She kept coming and going in her car from this house that we were in sometimes with the policeman; other times it was just busy with different unknown people. My friend was terrified and turned to me for help. At one point, she was wailing and pleading with me to help her, saying, “please don’t let them take me away.” I was holding her and comforting her and saying I wouldn’t let them do that."
        },
        {
           ref: "This Jungian Life Podcast, episode 161",
           text: "There are tarantulas stuck on my skin the way ticks would be. They are big and hairy. Strangely the tarantulas are hidden in small boxes, which hang on my body. So their legs are digging into my skin, but I can’t see them unless I remove the boxes. My mother is helping me to remove the spiders, but they keep coming back. They don’t crawl upon me but rather seem to be born from my skin. All of a sudden, my mother is gone, and I’m alone with some spiders still hanging on me. I can’t remove them myself because I’m too scared to touch them. I am terrified and helpless." 
        },
        {
            ref: "This Jungian Life Podcast, episode 178",
            text: "I am in the bathroom of a hotel room where I am staying. I may have just gotten out of the shower. I see a fat, red, slimy worm-like creature several inches in length crawling along the floor. I am horrified and think that it is a snake. As I inspect it more closely, I notice a tiny pair of limbs along the upper portion of the body. At this point, I wonder if it is a baby alligator. I find this idea less repugnant than a snake. My wife comes into the room and tells me that it is actually a bird. As I study the tiny limbs, I begin to think that these must be embryonic wings. At this point, I begin to ponder how I should nurture this creature, wondering if it would be best for it if I took it outside."
        },
        {
            ref: "This Jungian Life Podcast, episode 149",
            text: "I found a tiny fish in the sink. It was really beat up but alive, so I got a bowl of water for it and put it there, but it immediately started outgrowing the bowl. I got a bigger bowl but as soon as I put it there, the fish got bigger. I got a tub of water and put it there and it got even bigger. It had stripes and it was looking at me and interacting with me the whole time. This fish seemed to have a soul.”"
        },
        {
            ref: "This Jungian Life Podcast, episode 141",
            text: "I’m in a small underground room. Near the ceiling, in a shadowy corner, hangs a cocoon or nest. It looks like a felted mitten and contains sleeping baby bats. Frightened, I summon my husband and quietly point out the nest. He agrees that we should take care not to wake the baby bats—for even though they are tiny and blind, they are not vulnerable. I whisper the phrase “dangerous little experts.” We stand as still as we can in the dark. The next scene is outdoors and sunny. I’m in the middle of a street that is normally busy, but now empty. A snowy owl appears before me on the pavement. I again summon my husband, and as we admire the owl, five more snowies arrive. They grow until they stand about four feet tall, then begin hopping and spinning and flapping, almost like they’re performing a ceremonial Native American dance. I suspect they are children wearing feather costumes, but no, they really are owls. My husband and I are thrilled and honored. The street seems alive with magic."
        },
        {
            ref: "This Jungian Life Podcast, episode 138",
            text: "I was on a hospital bed, due to a heart attack. Doctors were trying to send an electric wave to measure my heart damage–and I was terrified of the pain it may cause. Doctors told me that if it hurts I need surgery immediately. I was watching the screen, and it didn’t hurt at all. Doctors told me that my heart was really strong and that I can go home. I felt relieved. Then a nurse walked over to me and handed a piece of paper, a note from someone, and said I have to go see this other patient. The note was from Su, a high school female friend that betrayed me, a person that I don’t think about at all. The note said that I need to take care of her babies. I was so confused. I walked over to the room, found her sitting on the bed. She pointed the babies to me and asked for help. I didn’t talk to her. She has just given birth, and 3 little bundles were in a crib next to her. I lifted the bundles and they didn’t look like babies, they were marble white and looked weird. Almost looked like the Hindu god with the elephant trunk- god Ganesh I think. I dropped them on the floor. I wanted to check whether they are real. I filled them with milk and said they are alive. I was so confused. I woke up."
        },
        {
            ref: "This Jungian Life Podcast, episode 133",
            text: "I’m standing outside of a pool and my sons (6 and 10) are in the pool with my ex-husband. My mother is sitting near me. I realize I need to go to the bathroom and shout to my ex-husband to take care of our youngest son. As I turn my back at the pool I see a frogman, he has the body of a man and the head of a frog. He is sitting as a frog on the floor. I’m surprised and fascinated by it. His skin is dark blue with small light green and light blue freckles. His eyes are green. It is raining and he seems to be enjoying the water. I call my brother so he can see the creature; my brother appears as a little boy and the frogman sits at a table with my brother that asks him many questions about his origin. The frogman speaks to my brother while I go to the bathroom. When I return the frogman is sitting on a small stairway, like waiting for me. I see him and I ask him if I can touch his skin. He lets me touch his arm; it is shiny and beautiful like a night full of stars. I don’t remember if I kiss him or hug him. He asks me to go with him and I tell him that I have other things to do. I walk down a street and find a busy avenue with heavy traffic. I have to cross to the other side but it seems hard, like a complex coordination of moves and traffic lights. I see the frogman walking on the other side of the avenue. "
        },
        {
            ref: "This Jungian Life Podcast, episode 129",
            text: "I was waiting for a young man to pick me up for our second date, but he was late. I was in a park and there was a fair, and I ran into some of my childhood friends who were quite surprised about my date. So they started harassing me with questions about who he was and, mostly, why he was late. I didn’t have his phone number, so I didn’t know. I had with me a backpack, laptop, kindle, handbag, another bag and my stuff kept falling on the ground, and I had to pick it up over and over. It was raining hard, hours had passed and I decided to walk through the fair. There I bought a unicorn-shaped mug, that immediately fell off my hands and became ash as it hit the ground. I was tired and cold and went sitting under a large tree. In the tall grass, emerged a group of people who were shooting at wild ducks."
        },
        {
            ref: "This Jungian Life Podcast, episode 119",
            text: "It is dusk and quickly becoming night. I am hidden from view, lying on my belly in a tunnel of some sort. I am looking out onto a clearing surrounded by trees. I see a small, fluffy, grey kitten–innocent, sweet. I want to climb out to hold the kitten and take care of it. Suddenly, a large, dark-brownish black bear lumbers in, crashing through the foliage; it doesn’t see me. I watch it, and am struck by how coarse the hair of his fur is and that the claws are ivory white but thick, strong and sharp. I stay hidden, watching. The bear moves away and as it does, turns into a wrinkled light grey elephant; it is small, but from my point of view it looks quietly significant as it treads by. I am still hidden from view and feel awestruck and numb watching all this. I look down; I appear to be lying on over-sized slate- green stepping stones–oblong, almost triangular. Then to my horror, the stones begin to slowly shift up and along the ground, undulating! I feel a mix of awe and fear when I realize that the stones are actually the scales of an enormous serpent/snake–and my reclining body is being carried along with it. "
        },
        {
            ref: "This Jungian Life Podcast, episode 114",
            text: "I was in a forest next to a fortress wall. A little boy appeared with a cotton hood over his head that covered his face. The child was riding a white pony. I could see his blue eyes through slits in the hood. They looked sideways. I don’t know if the child saw me, but he felt I was there because he clung to me. I hugged him and the pony with great love and tenderness. The child needed my love and protection. At that moment, a man in green clothes and armor approached me. Without being aggressive, he told me that I had to leave the child who was the king’s son and had his own guard. The man kindly invited me to go with him. I was divided in my feelings. I felt great love for the child, but I also felt guilt that I was breaking some high rules I didn’t understand. I followed the man, who was now dressed in a long red robe and looked like a royal nobleman. I was walking about 10 meters after him. We went around the fortress and took the streets of the city. We walked for a long time. He entered a building, I followed him at a distance. When I entered the building, I heard his voice from below, he was walking down the stone stairs. He told me to pass him a big black hook on a chain. I obeyed unquestioningly and handed him the hook. At that moment, for the first time, I doubted the man and his intentions. Horrified, I realized that, guided by my guilt, I was following a torturer who made his prey prepare their own torments. I realized that I had to do something right away and I regretted that I had not felt the threat before, when I could easily escape, because moving away after him, we were often in different places – for example, he had already entered the entrance, and I was still walking down the street. All I had to do was rush back up the stairs before entering his dungeon. I woke up in horror."
        },
        {
            ref: "This Jungian Life Podcast, episode 109",
            text: "I am on or in the ocean. Not sure how I got there or where I am going — also strangely not in something. From my left a huge ship appears. In the “window” of the ship there is an elephant and a giraffe next to each other. They “smile” at me as they pass me as if to say goodbye and there the ship disappears on the horizon. Then I wake up. I am now left with the image of Noah’s Ark but can’t make sense of the symbolism."
        },
        {
            ref: "This Jungian Life Podcast, episode 95",
            text: "I am going to become the next queen of England. But first, I had to clean a lot of food and trash from an audience seating area (like stands at a sports arena). I asked the Queen if I was making a mistake by becoming the next queen. She said yes, and that I will have no time to give to my own children (once I have them). A young male advisor to the Queen was assisting her and helping to set everything up for the transition. On a break from cleaning, I went down to a craft fair and visited some old ladies and talked to them about the beautiful art they made. My grandmother was there, trying to print a photograph I took of a Legislature building. I returned to my task and at 6:00 PM, I made my way to sit on the right arm of the Queen’s chair, ready for the ceremony. "
        }
    ]
}


const suggest = {
    setting: {
        title: "Suggestions for how to interpret dream setting",
        text: "The opening scene of a dream often gives us a sense of the inner landscape of the dreamer. A setting in a building or house may represent the psyche itself. A basement could stand in for the unconscious and the attic may house the superego. If it is your childhood home, this adds another layer of meaning. The setting of a childhood home may represent your own childhood or the dynamics of your family.\n\nA forest or body of water is often associated with the unconscious. So, a stroll through the woods or a dip in a lake may be stepping into the world of the unconscious.\n\nLook for associations with the time and place of a dream. Finding yourself in a medieval prison conveys something very different than a dream that takes place in 1969 at Woodstock. It is common for a dream to have several 'scenes', so each setting gives us more information as the dream unfolds."
    },
    characters: {
        title: "Suggestions for how to interpret characters in a dream.",
        text: "Figures in the dream may subjectively represent aspects of the dreamer's psyche or they may objectively correspond to people in the real world. If the figure is a person you know, first consider what that person might symbolize to you by examining the character's representational meaning. For instance, if my 4-year-old nephew is present in my dream, he might represent a creative project I have been working on for 4 years. On the other hand, it's possible that I just miss my nephew.\n\nIt is said that the dream ego is the least reliable character in the dream. It is worth paying attention to the messages from other dream figures and the dream environment. If other figures are angry, scared, or upset and my dream ego is laid-back, the other characters are a better gauge for what my unconscious is trying to tell me. Or, if my dream ego is angry or scared and the other dream figures seem unconcerned, the unconscious may be communicating that my worries are unwarranted.\n\nAnimals in a dream often stand in for instinctive or intuitive aspects of the psyche. A snake or a reptilian figure may represent a part of the dreamer that is more primal and less evolved than a rabbit or a bear. Since we often have mythical and symbolic associations with animals, they can be a rich source of dream metaphor from the unconscious."
    },
    symbols: {
        title: "Suggestions for how to interpret symbols in a dream.",
        text: "If there are particular images that stand out in a dream, it is a good exercise to explore all of the associations you have with those images. Many images are featured in fairy tales and myths and are therefore infused with archetypal significance. Associations may be specific to the dreamer’s culture. For example, in western thought, a rose may be a symbol for love or purity or the Virgin Mary, but if I was pruning roses a few days ago, a better reading of the rose in my dream could be associated with pruning or the thorns that scratched up my arms as I was gardening.\n\nThe unconscious often has a sense of humor, so it may deliver sly or obvious jokes to the dreamer through the use of symbolic puns."
    },
    shadow: {
        title: "Suggestions for how to interpret shadow in a dream",
        text: "In Jungian psychology, shadow is the part of the self that we try to supress. Since we tend to project our shadow onto other people, the Jungian analyst, James Hollis, suggests that if you want to know your shadow, you can just look to the traits you dislike in the people that really anger or annoy you. If our parents or caregivers looked down on things like creativity or vulnerability, these may also turn into psychic shadow.\n\nIn a dream, shadow may show up as an evil figure, such as a monster or ghost. It may appear as what we think of as 'other', such as a foreign land or an unfamiliar language. It may also show up as something we find disgusting, such as a dirty bathroom or fecal matter. Shadow can be a source of untapped potential, so it is important to notice it in a dream.\n\nTurning around to confront a shadow character that's chasing you and asking it what it wants, often leads to surprising results. Assimilating the shadow is hard work, but we are less likely to project our shadow onto others if we can make peace with our own shadow. That said, anyone with trauma, moderate anxiety, depression, or any other mental health issue should only tackle confronting their shadow under the guidance of a trained mental health professional"
    },
    motifs: {
        title: "Suggestions for how to interpret dream sentiment.",
        text: "The overall sentiment of a dream may be misleading. Dream studies have suggested that people tend to have more negatively biased dreams than positive ones. But just because the dream content is negative, doesn't mean the unconscious has a negative message for the dreamer. A scary dream may bring the dreamer closer to accepting a responsibility they've been avoiding, or help them find the assertive confidence to finally ask for a raise at work.\n\nFor a more thorough investigation of dream analysis, Robert Johnson's 'Inner Work Using Dreams and Active Imagination for Personal Growth' is a good place to start."
    }
}

module.exports = {
    sample_dreams,
    suggest
}